### ISSUE TITLE
bug: `validate_eth_tx` doesn't handle legacy transactions

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-ssj#610] opened 2023-12-05 12:04 UTC
## Bug Report

**Current behavior:**
The v value for legacy transactions is not corrected by the `chain_id`. 

**Expected behavior:**
For legacy transaction, the `y_parity` of the transaction should be extracted from the `v` field of the signature with the formula `y_parity = v - 2 * chain_id - 35`.

**Comment by enitrat** [comment] 2023-12-05 16:52
@bajpai244 can you take?

**Comment by bajpai244** [comment] 2023-12-05 16:53
@enitrat , you can assign me.

**Comment by bajpai244** [comment] 2023-12-08 11:27
We have to talk on this one in the weekly, because it is actually not a bug.

What the argument here is that, in case of legacy transactions, we should take V `and calculate `y_parity manually inside `__validate__` and `__execute__`.

I don't think any advantage to this as of now, because there is no need to prove extraction of `y_parity` from `v` and it just adds some extra cairo steps for this + some extra complexity on handeling the signature. I think extraction of y_parity from V is something which is better on the RPC itself as there is no advantage to prove this!

**Comment by Eikix** [comment] 2023-12-08 13:22
> We have to talk on this one in the weekly, because it is actually not a bug.
> 
> What the argument here is that, in case of legacy transactions, we should take V `and calculate `y_parity manually inside `__validate__` and `__execute__`.
> 
> I don't think any advantage to this as of now, because there is no need to prove extraction of `y_parity` from `v` and it just adds some extra cairo steps for this + some extra complexity on handeling the signature. I think extraction of y_parity from V is something which is better on the RPC itself as there is no advantage to prove this!

I personally disagree.

- First extracting `y_parity` out of `v` is only done once in `__validate__`, and it comprises 1 addition and 1 multiplication afaik.
- Second, it is part of the commitment scheme to extract `y_parity` since it contains the chain_id. Though you are right, I think it's somewhat redundant with the chain_id being part of the signed data. 

Nonetheless I think for now having this extraction part of the signature validation feels fine to me

**Comment by bajpai244** [comment] 2023-12-09 05:40
@Eikix , cool, I guess we can then do the extraction on `__validate__` ourselves!

I guess the new signature format can look like this:
```
[tx_type, r, s, v | y_parity ]
```

`tx_type = 0 | 1 | 2`

In `__validate__` if, `tx_type == 0`, we will extract out the `y_parity` from `v`, otherwise the value should be `y_parity` itself.

**Comment by Eikix** [comment] 2023-12-09 13:12
> @Eikix , cool, I guess we can then do the extraction on `__validate__` ourselves!
> 
> I guess the new signature format can look like this:
> 
> ```
> [tx_type, r, s, v | y_parity ]
> ```
> 
> `tx_type = 0 | 1 | 2`
> 
> In `__validate__` if, `tx_type == 0`, we will extract out the `y_parity` from `v`, otherwise the value should be `y_parity` itself.


I think since tx type is directly correlated with the way we parse a signature, we could:
1. Change signature of `TransactionMetadata`, and have `signature` field become a Span<felt252> like it currently is in `tx_info.signature`
2. Perform the extraction of `y_parity` around this line: https://github.com/kkrt-labs/kakarot-ssj/blob/main/crates/utils/src/eth_transaction.cairo#L263 using chain_id, and an if branch with `is_legacy_tx(encoded_tx_data)` and then you can perform the `signature.try_into()` there

Wdyt

**Comment by bajpai244** [comment] 2023-12-12 07:22
resolved via #643 .

**Closed by bajpai244** 2023-12-12 07:22 UTC
Labels: bug
